version: '3.8'

services:
  app:
    build: .
    container_name: flasky
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
